### PR TITLE
reinit layout on data change

### PR DESCRIPTION
**Pull request by dessant**
I'm not sure if this is the right place to do it, but it seems to fix the issues related to adding and removing items.

### CODE REVIEW

**Comment by tito** [comment]
It was one of the "best" optim i came up with, as when layout is done one time, there is no "need" to redo the layout from scratch when data change. 

Do you have a test case for this change?

**Comment by dessant** [comment]
@tito click fill, then add:

``` python
from kivy.config import Config
Config.set('modules', 'inspector', '')
# from _recycleview import RecycleView
from kivy.garden.recycleview import RecycleView
from kivy.base import runTouchApp
from kivy.lang import Builder
from kivy.app import App

KV = """
<ContactItem@Label>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 0.5
        Rectangle:
            pos: self.pos
            size: self.size

    color: 0, 0, 0, 0.5

BoxLayout:
    orientation: "vertical"
    BoxLayout:
        size_hint_y: None
        height: 30
        Button:
            text: "fill"
            on_release: app.generate_new_data()
        Button:
            text: "add"
            on_release: app.add_item()
        Button:
            text: "Remove first item"
            on_release: app.remove_item()
        Button:
            text: "Update first item"
            on_release: app.update_item()
    RecycleView:
        id: rv
        key_viewclass: 'viewclass'
        key_size: 'height'
"""


class RecycleViewApp(App):

    def build(self):
        return Builder.load_string(KV)

    def update_item(self):
        data = self.root.ids.rv.data[0]
        data['text'] = 'test'
        self.root.ids.rv.data[0] = data

    def add_item(self):
        data = self.root.ids.rv.data
        data.insert(len(data), {
                    "viewclass": "ContactItem",
                    "text": 'x' + str(len(data))})

    def remove_item(self):
        del self.root.ids.rv.data[0]

    def generate_new_data(self):
        contacts = []
        for x in range(10):
            contacts.append({
                "index": x,
                "viewclass": "ContactItem",
                "text": str(x)})
        self.root.ids.rv.data = contacts

RecycleViewApp().run()
```

**Comment by dessant** [comment]
Without this change, it is messed up. I agree that this is not a good fix, it just helps me use the widget until you do a proper fix :-P.

**Comment by tito** [comment]
ok, nice catch.

**Pull request merged**
